name: c64
description: Set of tools to compile 6502 assembly code for the Commodore 64.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  console: ^4.1.0
  quiver: ^3.2.1
  meta: ^1.9.1
  http: ^1.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
  build_runner: ^2.4.5
  build_test: ^2.1.7
  json_to_model: ^3.2.4
