name: dax64
description: Set of tools to compile 6502 assembly code for the Commodore 64.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.5.0
  console: ^4.1.0
  quiver: ^3.2.2
  meta: ^1.16.0
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  build_runner: ^2.4.12
  build_test: ^2.2.2
  json_to_model: ^3.2.4
