import 'dart:collection';
import 'dart:typed_data';

import 'package:dax64/assembler/addressing_modes.dart';
import 'package:dax64/assembler/assembler_config.dart';
import 'package:dax64/assembler/errors.dart';
import 'package:dax64/assembler/parser/operand_parser.dart';
import 'package:dax64/assembler/parser/parser.dart';
import 'package:dax64/models/asm_program.dart';
import 'package:dax64/models/generated/index.dart';
import 'package:dax64/utils/hex8bit.dart';

import '../models/statement/assembly.dart';
import '../models/statement/empty.dart';
import '../models/statement/label.dart';
import '../models/statement/macro.dart';

class Assembler {
  final Opcodes opcodes;
  final Map<String, Instruction> opcodeMap = {};

  Assembler({required this.opcodes}) {
    for (var instruction in opcodes.instructions) {
      opcodeMap[instruction.instruction] = instruction;
    }
  }

  Uint8List assemble(String input) {
    final config = AssemblerConfig(opcodes: opcodes);
    final program = Parser(config: config).parse(input);

    // we need to go through program twice
    //  - 1st round to find all labels and macro statement (TODO impl)
    //  - 2nd round to expand lab

    // TODO first round here

    // TODO at first stage support just assembly statements
    //  - at 2nd phase data blocks
    //  - then macros
    // TODO final plan!!
    //  1) go through to find all assignments and labels (and later macros)
    //  2) then expand values and parse operands
    //  3) then assemble

    // TODO how macro invocations is recognized and when it is expanded?

    // label points to line number because a label may me located on its own
    // line, and refers to next instructions line, or it maybe combined to
    // same line with instruction

    // TODO this doesn't solve actual getting address

    // TODO some design thoughts
    //   Regs
    //     - label can be introduced after current line. For example
    //       subroutine where to jump
    //
    //   Impl
    //     - right now we don't memory address for label
    //     - we know starting address of a block (TODO impl)
    //     - we can count lines, and if label ref is to previously
    //       introduced label then everything is ok
    //     - but if we don't know memory address yet?
    //
    //     - possible solutions:
    //       a) change parsing phase
    //       b) second round
    //       c) third round
    //       d) partial third round
    //
    //     - open how zero page affects? Affects to generated bytes
    //
    //     - we can also refer by variables if we want to point
    //       address on zero page, but our code could put there data
    //       or even executable code...
    //
    //     - Note that if compiling one binary block then it needs to
    //       continuous. But with basic loaders we could support multiple
    //       separate blocks

    final bytes = secondRoundAssemble(program);

    return Uint8List.fromList(bytes);
  }

  // TeroV following doesn't work as label could be in its own line
  AssemblyContext buildAssemblyContext(AsmProgram program) {
    return AssemblyContext.fromProgram(program);
  }

  // collects labels
  // TODO add value object
  Map<String, AsmProgramLine> firstRoundCollectData(AsmProgram program) {
    final labels = <String, AsmProgramLine>{};

    for (final block in program.blocks) {
      for (final line in block.lines) {
        try {
          switch (line.statement) {
            case final AssemblyStatement statement:
              if (statement.hasLabel()) {
                labels[statement.label] = line;
              }
              break;

            case final MacroStatement _:
              // TODO collect macros and macro assignments
              throw UnimplementedError('Macro statements not yet implemented');

            case final LabelStatement statement:
              labels[statement.label] = line;
              break;

            case final EmptyStatement _:
              // empty statements do not contain labels, label is part of
              // AssemblyStatement
              // TODO: which above is a bit funny as line with just a label is
              // not generated to any assembly output... label should actually
              // be part of next statement...
              continue;
          }
        } catch (e, stacktrace) {
          // TODO with verbose flag print stacktrace
          print(e);
          print(stacktrace);

          throw AssemblerError(
              'Error on line ${line.lineNumber}: ${line.originalLine}. $e');
        }
      }
    }

    return labels;
  }

  List<int> secondRoundAssemble(AsmProgram program) {
    // TODO impl using labels

    // TODO pass info about labels and macros, and memory address

    final bytes = <int>[];
    for (final block in program.blocks) {
      for (final line in block.lines) {
        try {
          switch (line.statement) {
            case final AssemblyStatement statement:
              var statementBytes = assembleAssemblyStatement(statement);
              bytes.addAll(statementBytes);
              break;

            case final MacroStatement _:
              throw UnimplementedError('Macro statements not yet implemented');

            // plain labels do not generate any assembly output
            case final LabelStatement _:
            case final EmptyStatement _:
              // empty statements do not generate any assembly output
              continue;
          }
        } catch (e, stacktrace) {
          // TODO with verbose flag print stacktrace
          print(e);
          print(stacktrace);

          throw AssemblerError(
              'Error on line ${line.lineNumber}: ${line.originalLine}. $e');
        }
      }
    }

    return bytes;
  }

  List<int> assembleAssemblyStatement(AssemblyStatement statement) {
    if (!statement.shouldAssemble) return [];
    final bytes = <int>[];

    switch (statement) {
      case AssemblyInstruction(
          :var opcode,
          :var instructionSpec,
          :var operand?
        ):
        bytes.add(parse8BitHex(opcode.opcode));

        // operand value is string - it could be label or macro ref, but
        // that is not yet implemented for assembling output

        // special case for relative addressing mode
        if (isRelativeJumpInstruction(instructionSpec) &&
            operand.addressingMode == AddressingMode.absolute) {
          throw NotImplementedAssemblerError(
              'Relative addressing mode not implemented for instruction: ${instructionSpec.instruction}');
        }

        final operandBytes =
            parseOperandValue(operand.addressingMode, operand.value);

        bytes.addAll(operandBytes);

        break;

      case AssemblyInstruction(:var opcode):
        // no operands
        // TODO "opcode"*2 is not the naming BEST
        bytes.add(parse8BitHex(opcode.opcode));
        break;

      case final AssemblyData _:
        break;

      default:
        break;
    }

    return bytes;
  }

  bool isRelativeJumpInstruction(Instruction instruction) {
    return instruction.opcodes
        .every((element) => element.addressMode.endsWith("Rela"));
  }
}

// TeroV do we have away to support multiple memory blocks?
//   - yes with BASIC loader it is possible, but when outputting just binary not
//     - we would also need a meta file to describe starting addresses of
//       different blocks

// TODO do we need assembly context?
class AssemblyContext {
  final int startingMemoryAddress;

  // TeroV as label can be on empty line, do we calculate real line it is pointing?
  //       or in fact should label just be a relative address value?
  final Map<LabelName, AsmProgramLine> labels;
  final Map<VariableName, MacroAssignment> variables;
  final Map<MacroName, MacroDefinition> macros;

  AssemblyContext(
      this.startingMemoryAddress, this.labels, this.variables, this.macros);

  static fromProgram(AsmProgram program) {
    // TeroV how starting memory address is defined?

    final startingMemoryAddress = 0x8000; // TODO just some value here
    final Map<LabelName, AsmProgramLine> labels = HashMap();
    final Map<VariableName, MacroAssignment> variables = HashMap();
    final Map<MacroName, MacroDefinition> macros = HashMap();

    for (final block in program.blocks) {
      // TODO not sure how blocks are affected
      for (final line in block.lines) {
        // TODO not sure why label can't be null (or Option)
        if (line.statement.label.isNotEmpty) {
          labels[line.statement.label] = line;

          if (line.statement is MacroAssignment) {
            final assignment = line.statement as MacroAssignment;
            variables[assignment.name] = assignment;
          } else if (line.statement is MacroDefinition) {
            final macro = line.statement as MacroDefinition;
            macros[macro.name] = macro;
          }
        }
      }
    }
    return AssemblyContext(startingMemoryAddress, labels, variables, macros);
  }
}

typedef LabelName = String;
typedef VariableName = String;
typedef MacroName = String;
