name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]
  push:
    brances: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.5.3

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test

      - run: sudo apt install vice
      - run: ./test_execution_flow.sh
              
